[workspace]
members = [
  "ella",
  "ella-parser",
  "ella-passes",
  "ella-source",
  "ella-value",
  "ella-vm",
]

[profile.release]
# Uncomment when debugging or profiling release build
# debug = true
